#
# If true install in single namespace mode
#
limitNamespace: false

ingress:
  enabled: false
  # hosts:
  #   - host: kubeview.example.net
  #     paths:
  #       - /
  # tls:
  #  - secretName: my-cert
  #    hosts:
  #      - kubeview.example.net

loadBalancer:
  enabled: true

  IP: '1.2.3.4'
