name: Release Assets

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  dockerUser: bencuk
  imageName: kubeview

jobs:
  release:
    name: Release image & chart
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file ./build/Dockerfile --build-arg version="${{ github.event.release.tag_name }}" --build-arg buildInfo="GitHub release build dated:$(date -I)" --tag ghcr.io/$GITHUB_ACTOR/$imageName:${{ github.event.release.tag_name }}

      - name: Push to Github registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/$GITHUB_ACTOR/$imageName:${{ github.event.release.tag_name }}

      - name: Package Helm chart
        run: helm package kubeview
        working-directory: ./charts

      - name: Update chart index
        run: helm repo index .
        working-directory: ./charts

      - name: Update repo with output
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Helm chart to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./charts/kubeview-${{ github.event.release.tag_name }}.tgz
          asset_name: kubeview-${{ github.event.release.tag_name }}.tgz
          asset_content_type: application/octet-stream
