name: Build Dockerhub Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  imageName: kubeview
  imageTag: latest

# Note. CI build only builds 'latest' image, not the semver release

jobs:
  build:
    name: Check and CI build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Check server code with gofmt
        run: bash .github/workflows/gofmt-action.sh cmd/server

      - name: Build the Docker image
        run: docker build . --file ./build/Dockerfile --build-arg buildInfo="GitHub CI build $GITHUB_RUN_ID, of $GITHUB_REF on $(date -I)" --tag ghcr.io/$GITHUB_ACTOR/$imageName:$imageTag

      - name: Push to Github registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/$GITHUB_ACTOR/$imageName:$imageTag
